version: "3"

services:
  ${containers.nginx}:
    image: nginx:latest
    container_name: ${containers.nginx}
    depends_on:
      - ${containers.frontend}
      - ${containers.portainer}
    volumes:
      - "${folders.containers.nginx}/frontend.conf:/etc/nginx/nginx.conf"
      - "${folders.containers.nginx}:/etc/nginx"
      - "${folders.containers.docker_compose.frontend.certbot_data.www}:/var/www/certbot/"
      - "${folders.containers.docker_compose.frontend.certbot_data.conf}:/etc/nginx/ssl/"
    ports:
      - "${ports.http}:${ports.http}"
      - "${ports.https}:${ports.https}"
    
  ${containers.certbot}:
    image: certbot/certbot:latest
    volumes:
      - ${folders.containers.docker_compose.frontend.certbot_data.www}:/var/www/certbot/
      - ${folders.containers.docker_compose.frontend.certbot_data.conf}:/etc/letsencrypt/

  ${containers.frontend}:
    image: ${containers.frontend}
    container_name: ${containers.frontend}
    build:
      context: "${folders.services.frontend}"
      args:
        FRONTEND_PORT: ${ports.frontend}
    volumes:
      - "${folders.services.frontend}:/app"
    ports:
      - "${ports.frontend}:${ports.frontend}"
    restart: on-failure

  ${containers.portainer}:
    image: portainer/portainer-ce:latest
    container_name: ${containers.portainer}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${folders.containers.docker_compose.frontend.portainer_data}:/data
    ports:
      - ${ports.portainer}:${ports.portainer}