version: "3"

services:
  "${containers.nginx}":
    image: nginx:latest
    container_name: ${containers.nginx}
    depends_on:
      - ${containers.frontend}
      - ${containers.portainer}
    volumes:
      - "${folders.infrastructure.frontend.nginx}/frontend.conf:/etc/nginx/nginx.conf"
      - "${folders.infrastructure.nginx}/http.conf:/etc/nginx/http.conf"
      - "${folders.infrastructure.nginx}/https.conf:/etc/nginx/https.conf"
      - "${folders.infrastructure.nginx}/globals.conf:/etc/nginx/globals.conf"
      - "${folders.infrastructure.nginx}/portainer.conf:/etc/nginx/portainer.conf"
      - "${folders.infrastructure.nginx}/proxy.conf:/etc/nginx/proxy.conf"
      - "${folders.infrastructure.frontend.certbot_data.www}:/var/www/certbot/"
      - "${folders.infrastructure.frontend.certbot_data.conf}:/etc/nginx/ssl/"
    ports:
      - "${ports.http}:${ports.http}"
      - "${ports.https}:${ports.https}"

  "${containers.certbot}":
    image: certbot/certbot:latest
    volumes:
      - ${folders.infrastructure.frontend.certbot_data.www}:/var/www/certbot/
      - ${folders.infrastructure.frontend.certbot_data.conf}:/etc/letsencrypt/

  "${containers.frontend}":
    image: ${containers.frontend}
    container_name: ${containers.frontend}
    build:
      context: "${folders.services.frontend}"
      args:
        FRONTEND_PORT: ${ports.frontend}
    volumes:
      - "${folders.services.frontend}:/app"
    ports:
      - "${ports.frontend}:${ports.frontend}"
    restart: on-failure

  "${containers.portainer}":
    image: portainer/portainer-ce:latest
    container_name: ${containers.portainer}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${folders.infrastructure.frontend.portainer_data}:/data
    ports:
      - ${ports.portainer}:${ports.portainer}
