\connect ${postgres.weather.name};
CREATE TABLE IF NOT EXISTS ${postgres.weather.tables.daily} (
    id                           SERIAL PRIMARY KEY,
    timestamp                    TIMESTAMP NOT NULL UNIQUE, 
    sunrise                      TIMESTAMP NOT NULL,
    sunset                       TIMESTAMP NOT NULL,
    moonrise                     TIMESTAMP NOT NULL,  
    moonset                      TIMESTAMP NOT NULL, 
    moon_phase                   NUMERIC(8,4) NOT NULL,
    temperature                  NUMERIC(8,4) NOT NULL,
    temperature_night            NUMERIC(8,4) NOT NULL,
    temperature_evening          NUMERIC(8,4) NOT NULL,
    temperature_morning          NUMERIC(8,4) NOT NULL,
    temperature_min              NUMERIC(8,4) NOT NULL,
    temperature_max              NUMERIC(8,4) NOT NULL,
    apparent_temperature         NUMERIC(8,4) NOT NULL,
    apparent_temperature_night   NUMERIC(8,4) NOT NULL,
    apparent_temperature_evening NUMERIC(8,4) NOT NULL,
    apparent_temperature_morning NUMERIC(8,4) NOT NULL,
    pressure                     INTEGER NOT NULL,
    humidity                     INTEGER NOT NULL,
    dew_point                    NUMERIC(8,4) NOT NULL,
    cloud_coverage               NUMERIC(8,4) NOT NULL,
    visibility                   NUMERIC(8,4),
    wind_speed                   INTEGER NOT NULL,
    wind_direction               NUMERIC(8,4) NOT NULL,
    owm_weather_id               INTEGER NOT NULL,
    owm_weather_title            TEXT NOT NULL,
    owm_weather_description      TEXT NOT NULL,
    chance_of_rain               NUMERIC(8,4) NOT NULL,
    wind_gust                    NUMERIC(8,4),
    uv_index                     NUMERIC(8,4)
);