version: "3"

services:
  "${containers.nginx}":
    image: nginx:latest
    container_name: ${containers.nginx}
    depends_on:
      - ${containers.iot_scraper}
      - ${containers.utilities_scraper}
      - ${containers.weather_scraper}
      - ${containers.portainer}
    volumes:
      - "${folders.infrastructure.scrapers.nginx}/iot_scraper.conf:/etc/nginx/iot_scraper.conf"
      - "${folders.infrastructure.scrapers.nginx}/utilities_scraper.conf:/etc/nginx/utilities_scraper.conf"
      - "${folders.infrastructure.scrapers.nginx}/weather_scraper.conf:/etc/nginx/weather_scraper.conf"
      - "${folders.infrastructure.scrapers.nginx}/scrapers.conf:/etc/nginx/nginx.conf"
      - "${folders.infrastructure.nginx}/http.conf:/etc/nginx/http.conf"
      - "${folders.infrastructure.nginx}/https.conf:/etc/nginx/https.conf"
      - "${folders.infrastructure.nginx}/globals.conf:/etc/nginx/globals.conf"
      - "${folders.infrastructure.nginx}/portainer.conf:/etc/nginx/portainer.conf"
      - "${folders.infrastructure.nginx}/proxy.conf:/etc/nginx/proxy.conf"
      - "${folders.infrastructure.scrapers.certbot_data.www}:/var/www/certbot/"
      - "${folders.infrastructure.scrapers.certbot_data.conf}:/etc/nginx/ssl/"
    ports:
      - "${ports.http}:${ports.http}"
      - "${ports.https}:${ports.https}"

  "${containers.certbot}":
    image: certbot/certbot:latest
    volumes:
      - ${folders.infrastructure.scrapers.certbot_data.www}:/var/www/certbot/
      - ${folders.infrastructure.scrapers.certbot_data.conf}:/etc/letsencrypt/

  "${containers.iot_scraper}":
    image: ${containers.iot_scraper}
    container_name: ${containers.iot_scraper}
    build:
      context: "${folders.services.iot.scraper}"
      args:
        iot_scraper_PORT: ${ports.iot_scraper}
    volumes:
      - "${folders.services.iot.scraper}:/app"
    ports:
      - "${ports.iot_scraper}:${ports.iot_scraper}"
    restart: on-failure

  "${containers.utilities_scraper}":
    image: ${containers.utilities_scraper}
    container_name: ${containers.utilities_scraper}
    build:
      context: "${folders.services.utilities.scraper}"
      args:
        UTILITIES_SCRAPER_PORT: ${ports.utilities_scraper}
    volumes:
      - "${folders.services.utilities.scraper}:/app"
    ports:
      - "${ports.utilities_scraper}:${ports.utilities_scraper}"
    restart: on-failure

  "${containers.weather_scraper}":
    image: ${containers.weather_scraper}
    container_name: ${containers.weather_scraper}
    build:
      context: "${folders.services.weather.scraper}"
      args:
        WEATHER_SCRAPER_PORT: ${ports.weather_scraper}
    volumes:
      - "${folders.services.weather.scraper}:/app"
    ports:
      - "${ports.weather_scraper}:${ports.weather_scraper}"
    restart: on-failure

  "${containers.portainer}":
    image: portainer/portainer-ce:latest
    container_name: ${containers.portainer}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${folders.infrastructure.scrapers.portainer_data}:/data
    ports:
      - ${ports.portainer}:${ports.portainer}
