version: "3"

networks:
  internal:
    internal: true
    driver: bridge

  external:
    external: true
    driver: bridge

services:
  "${containers.scrapers.nginx}":
    image: nginx:latest
    container_name: ${containers.scrapers.nginx}
    depends_on:
      - ${containers.scrapers.certbot}
      - ${containers.scrapers.devices}
      # - ${containers.scrapers.utilities}
      # - ${containers.scrapers.weather}
      - ${containers.scrapers.portainer}
    volumes:
      - "${folders.infrastructure.scrapers.nginx}/devices_scraper.conf:/etc/nginx/devices_scraper.conf"
      # - "${folders.infrastructure.scrapers.nginx}/utilities_scraper.conf:/etc/nginx/utilities_scraper.conf"
      # - "${folders.infrastructure.scrapers.nginx}/weather_scraper.conf:/etc/nginx/weather_scraper.conf"
      - "${folders.infrastructure.scrapers.nginx}/scrapers.conf:/etc/nginx/nginx.conf"
      - "${folders.infrastructure.nginx}/http.conf:/etc/nginx/http.conf"
      - "${folders.infrastructure.nginx}/https.conf:/etc/nginx/https.conf"
      - "${folders.infrastructure.nginx}/globals.conf:/etc/nginx/globals.conf"
      - "${folders.infrastructure.nginx}/portainer.conf:/etc/nginx/portainer.conf"
      - "${folders.infrastructure.nginx}/proxy.conf:/etc/nginx/proxy.conf"
      - "${folders.infrastructure.scrapers.certbot_data.www}:/var/www/certbot/"
      - "${folders.infrastructure.scrapers.certbot_data.conf}:/etc/nginx/ssl/"
    ports:
      - "${ports.scrapers.nginx}:${ports.http}"
      # - "${ports.https}:${ports.https}"
    networks:
      - internal
      - external

  "${containers.scrapers.certbot}":
    image: certbot/certbot:latest
    container_name: ${containers.scrapers.certbot}
    volumes:
      - ${folders.infrastructure.scrapers.certbot_data.www}:/var/www/certbot/
      - ${folders.infrastructure.scrapers.certbot_data.conf}:/etc/letsencrypt/
    networks:
      - internal

  "${containers.scrapers.devices}":
    image: ${containers.scrapers.devices}
    container_name: ${containers.scrapers.devices}
    build:
      context: "${folders.services.iot.devices_scraper}"
      args:
        DEVICES_SCRAPER_PORT: ${ports.scrapers.devices}
    environment:
      DEVICES_SCRAPER_PORT: ${ports.scrapers.devices}
    volumes:
      - "${folders.services.iot.devices_scraper}:/app"
    ports:
      - "${ports.scrapers.devices}:${ports.scrapers.devices}"
    restart: on-failure
    networks:
      - internal
      - external

  # "${containers.scrapers.utilities}":
  #   image: ${containers.scrapers.utilities}
  #   container_name: ${containers.scrapers.utilities}
  #   build:
  #     context: "${folders.services.utilities.scraper}"
  #     args:
  #       UTILITIES_SCRAPER_PORT: ${ports.scrapers.utilities}
  #   volumes:
  #     - "${folders.services.utilities.scraper}:/app"
  #   ports:
  #     - "${ports.scrapers.utilities}:${ports.scrapers.utilities}"
  #   restart: on-failure
  #   networks:
  #     - internal

  # "${containers.scrapers.weather}":
  #   image: ${containers.scrapers.weather}
  #   container_name: ${containers.scrapers.weather}
  #   build:
  #     context: "${folders.services.weather.scraper}"
  #     args:
  #       WEATHER_SCRAPER_PORT: ${ports.scrapers.weather}
  #   volumes:
  #     - "${folders.services.weather.scraper}:/app"
  #   ports:
  #     - "${ports.scrapers.weather}:${ports.scrapers.weather}"
  #   restart: on-failure
  #   networks:
  #     - internal

  "${containers.scrapers.portainer}":
    image: portainer/portainer-ce:latest
    container_name: ${containers.scrapers.portainer}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${folders.infrastructure.scrapers.portainer_data}:/data
    ports:
      - ${ports.portainer}:${ports.portainer}
    networks:
      - internal
