version: "3.9"
services:
  siyuan:
    image: b3log/siyuan
    command: ['--workspace=/siyuan/workspace/', '--accessAuthCode=password']
    container_name: siyuan
    ports:
      - 6806:6806
    volumes:
      - ./data:/siyuan/workspace
    restart: unless-stopped
    environment:
      # A list of time zone identifiers can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=GB

networks:
  proxy:
    external: true