services:
  {{ hosts.network.homepage.container }}:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: {{ hosts.network.homepage.container }}
    ports:
      - {{ hosts.network.homepage.port }}:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
