# TLS docs https://mindsers.blog/post/https-using-nginx-certbot-docker/

version: "3"

services:
  ${containers.nginx}:
    image: nginx:latest
    container_name: ${containers.nginx}
    depends_on:
      - ${containers.certbot}
      - ${containers.iot_api}
      - ${containers.utilities_api}
      - ${containers.weather_api}
      - ${containers.portainer}
    volumes:
      - "${folders.containers.nginx}/apis.conf:/etc/nginx/nginx.conf"
      - "${folders.containers.nginx}:/etc/nginx"
      - "${folders.containers.docker_compose.apis.certbot_data.www}:/var/www/certbot/"
      - "${folders.containers.docker_compose.apis.certbot_data.conf}:/etc/nginx/ssl/"
    ports:
      - "${ports.http}:${ports.http}"
      - "${ports.https}:${ports.https}"
    
  ${containers.certbot}:
    image: certbot/certbot:latest
    volumes:
      - ${folders.containers.docker_compose.apis.certbot_data.www}:/var/www/certbot/
      - ${folders.containers.docker_compose.apis.certbot_data.conf}:/etc/letsencrypt/
    
  ${containers.postgres}:
    image: postgres:latest
    container_name: ${containers.postgres}
    environment:
      - POSTGRES_USER=${postgres.root.user}
      - POSTGRES_PASSWORD=${postgres.root.password}
      - POSTGRES_PORT=${ports.postgres}
      - IOT_DB_USER=${postgres.iot.user}
      - IOT_DB_PASS=${postgres.iot.password}
      - IOT_DB_NAME=${postgres.iot.name}
      - UTILITIES_DB_USER=${postgres.utilities.user}
      - UTILITIES_DB_PASS=${postgres.utilities.password}
      - UTILITIES_DB_NAME=${postgres.utilities.name}
      - WEATHER_DB_USER=${postgres.weather.user}
      - WEATHER_DB_PASS=${postgres.weather.password}
      - WEATHER_DB_NAME=${postgres.weather.name}
    volumes: 
      - ${folders.containers.docker_compose.apis.postgres_data}:/var/lib/postgresql/data
      - ${folders.services.postgres.patches}:/docker-entrypoint-initdb.d
    ports:
      - "${ports.postgres}:${ports.postgres}"

  ${containers.redis}:
    image: redis:latest
    container_name: ${containers.redis}
    command: redis-server --port ${ports.redis}
    volumes:
      - ./redis-data:/var/lib/redis
    ports:
      - "${ports.redis}:${ports.redis}"
    
  ${containers.authorisation_api}:
    image: ${containers.authorisation_api}
    container_name: ${containers.authorisation_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.authorisation.api}"
      args:
        AUTHORISATION_API_PORT: ${ports.authorisation_api}
    environment:
      AUTHORISATION_API_PORT: ${ports.authorisation_api}
    volumes:
      - "${folders.services.authorisation.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.authorisation_api}:${ports.authorisation_api}"
    restart: on-failure
    
  ${containers.iot_api}:
    image: ${containers.iot_api}
    container_name: ${containers.iot_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.iot.api}"
      args:
        IOT_API_PORT: ${ports.iot_api}
    environment:
      IOT_API_PORT: ${ports.iot_api}
    volumes:
      - "${folders.services.iot.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.iot_api}:${ports.iot_api}"
    restart: on-failure

  ${containers.utilities_api}:
    image: ${containers.utilities_api}
    container_name: ${containers.utilities_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.utilities}/api"
      args:
        UTILITIES_API_PORT: ${ports.utilities_api}
    environment:
      UTILITIES_API_PORT: ${ports.utilities_api}
    volumes:
      - "${folders.services.utilities.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.utilities_api}:${ports.utilities_api}"
    restart: on-failure

  ${containers.weather_api}:
    image: ${containers.weather_api}
    container_name: ${containers.weather_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.weather}/api"
      args:
        WEATHER_API_PORT: ${ports.weather_api}
    environment:
      WEATHER_API_PORT: ${ports.weather_api}
    volumes:
      - "${folders.services.weather.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.weather_api}:${ports.weather_api}"
    restart: on-failure

  ${containers.portainer}:
    image: portainer/portainer-ce:latest
    container_name: ${containers.portainer}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${folders.containers.docker_compose.apis.portainer_data}:/data
    ports:
      - ${ports.portainer}:${ports.portainer}