# TLS docs https://mindsers.blog/post/https-using-nginx-certbot-docker/

version: "3"

networks:
  internal:
    internal: true
    driver: bridge

  external:
    driver: bridge

services:
  "${containers.nginx}":
    image: nginx:latest
    container_name: ${containers.nginx}
    depends_on:
      - ${containers.certbot}
      - ${containers.iot_api}
      - ${containers.utilities_api}
      - ${containers.weather_api}
      - ${containers.portainer}
    volumes:
      - "${folders.infrastructure.apis.nginx}/authorisation_api.conf:/etc/nginx/authorisation_api.conf"
      - "${folders.infrastructure.apis.nginx}/iot_api.conf:/etc/nginx/iot_api.conf"
      - "${folders.infrastructure.apis.nginx}/weather_api.conf:/etc/nginx/weather_api.conf"
      - "${folders.infrastructure.apis.nginx}/utilities_api.conf:/etc/nginx/utilities_api.conf"
      - "${folders.infrastructure.apis.nginx}/apis.conf:/etc/nginx/nginx.conf"
      - "${folders.infrastructure.nginx}/http.conf:/etc/nginx/http.conf"
      - "${folders.infrastructure.nginx}/https.conf:/etc/nginx/https.conf"
      - "${folders.infrastructure.nginx}/globals.conf:/etc/nginx/globals.conf"
      - "${folders.infrastructure.nginx}/portainer.conf:/etc/nginx/portainer.conf"
      - "${folders.infrastructure.nginx}/proxy.conf:/etc/nginx/proxy.conf"
      - "${folders.infrastructure.apis.certbot_data.www}:/var/www/certbot/"
      - "${folders.infrastructure.apis.certbot_data.conf}:/etc/nginx/ssl/"
    ports:
      - "${ports.http}:${ports.http}"
      - "${ports.https}:${ports.https}"
    networks:
      - internal
      - external

  "${containers.certbot}":
    image: certbot/certbot:latest
    volumes:
      - ${folders.infrastructure.apis.certbot_data.www}:/var/www/certbot/
      - ${folders.infrastructure.apis.certbot_data.conf}:/etc/letsencrypt/

  "${containers.postgres}":
    image: postgres:latest
    container_name: ${containers.postgres}
    environment:
      - POSTGRES_USER=${postgres.root.user}
      - POSTGRES_PASSWORD=${postgres.root.password}
      - POSTGRES_PORT=${ports.postgres}
      - IOT_DB_USER=${postgres.iot.user}
      - IOT_DB_PASS=${postgres.iot.password}
      - IOT_DB_NAME=${postgres.iot.name}
      - UTILITIES_DB_USER=${postgres.utilities.user}
      - UTILITIES_DB_PASS=${postgres.utilities.password}
      - UTILITIES_DB_NAME=${postgres.utilities.name}
      - WEATHER_DB_USER=${postgres.weather.user}
      - WEATHER_DB_PASS=${postgres.weather.password}
      - WEATHER_DB_NAME=${postgres.weather.name}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ${folders.services.postgres.patches}:/docker-entrypoint-initdb.d
    ports:
      - "${ports.postgres}:${ports.postgres}"
    networks:
      - internal

  "${containers.redis}":
    image: redis:latest
    container_name: ${containers.redis}
    command: redis-server --port ${ports.redis}
    volumes:
      - ./redis-data:/var/lib/redis
    ports:
      - "${ports.redis}:${ports.redis}"
    networks:
      - internal

  "${containers.authorisation_api}":
    image: ${containers.authorisation_api}
    container_name: ${containers.authorisation_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.authorisation.api}"
      args:
        AUTHORISATION_API_PORT: ${ports.authorisation_api}
    environment:
      AUTHORISATION_API_PORT: ${ports.authorisation_api}
    volumes:
      - "${folders.services.authorisation.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.authorisation_api}:${ports.authorisation_api}"
    restart: on-failure
    networks:
      - internal

  "${containers.iot_api}":
    image: ${containers.iot_api}
    container_name: ${containers.iot_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.iot.api}"
      args:
        IOT_API_PORT: ${ports.iot_api}
    environment:
      IOT_API_PORT: ${ports.iot_api}
    volumes:
      - "${folders.services.iot.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.iot_api}:${ports.iot_api}"
    restart: on-failure
    networks:
      - internal

  "${containers.utilities_api}":
    image: ${containers.utilities_api}
    container_name: ${containers.utilities_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.utilities}/api"
      args:
        UTILITIES_API_PORT: ${ports.utilities_api}
    environment:
      UTILITIES_API_PORT: ${ports.utilities_api}
    volumes:
      - "${folders.services.utilities.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.utilities_api}:${ports.utilities_api}"
    restart: on-failure
    networks:
      - internal

  "${containers.weather_api}":
    image: ${containers.weather_api}
    container_name: ${containers.weather_api}
    depends_on:
      - ${containers.postgres}
      - ${containers.redis}
    build:
      context: "${folders.services.weather}/api"
      args:
        WEATHER_API_PORT: ${ports.weather_api}
    environment:
      WEATHER_API_PORT: ${ports.weather_api}
    volumes:
      - "${folders.services.weather.api}:/app"
      - "${folders.shared}:/app/shared"
    ports:
      - "${ports.weather_api}:${ports.weather_api}"
    restart: on-failure
    networks:
      - internal

  "${containers.portainer}":
    image: portainer/portainer-ce:latest
    container_name: ${containers.portainer}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${folders.infrastructure.apis.portainer_data}:/data
    ports:
      - ${ports.portainer}:${ports.portainer}
    networks:
      - internal
